import { SVGProps } from "react";
import IconSet from "./IconSet";

export type IconSize = "xs" | "sm" | "md" | "lg" | "xl" | "xxl";

export type IconName =
  | "abc"
  | "apple"
  | "apple_pay"
  | "auto_withdraw"
  | "award"
  | "back_seats"
  | "bill"
  | "business"
  | "calendar"
  | "camera_b"
  | "camera_c"
  | "camera_d"
  | "canada"
  | "cancel"
  | "car_back"
  | "car_charge"
  | "car_child"
  | "car_fuel"
  | "car_mileage"
  | "car_pet"
  | "car_seat"
  | "car_trunk"
  | "car_type"
  | "card"
  | "card_a"
  | "card_c"
  | "cash"
  | "change"
  | "chat"
  | "chat_a"
  | "check"
  | "check_a"
  | "chevron_down"
  | "chevron_up"
  | "close"
  | "close_a"
  | "color"
  | "coordinates"
  | "copy"
  | "correct"
  | "delete"
  | "doc"
  | "documents_verified"
  | "dollar"
  | "dot"
  | "double_check"
  | "download"
  | "drag_area"
  | "edit"
  | "email"
  | "empty"
  | "eye"
  | "eye_closed"
  | "facebook"
  | "favorites"
  | "favorites_a"
  | "favorites_b"
  | "first_name"
  | "front_seats"
  | "goal"
  | "google"
  | "google_pay"
  | "image"
  | "information"
  | "information_a"
  | "last_name"
  | "licence_plate"
  | "loading"
  | "location_pin"
  | "location_pin_a"
  | "logout"
  | "menu"
  | "minus"
  | "more"
  | "multi_stops"
  | "navigation"
  | "no_cash"
  | "notification"
  | "number"
  | "passport"
  | "password"
  | "pause"
  | "paypal"
  | "phone_a"
  | "phone_b"
  | "phone_c"
  | "plus"
  | "plus_a"
  | "point_a"
  | "point_b"
  | "point_c"
  | "post"
  | "profile"
  | "progress"
  | "promo"
  | "promo_applied"
  | "question"
  | "repeat"
  | "report"
  | "return"
  | "reverse"
  | "ride"
  | "route"
  | "search"
  | "settings"
  | "settings_a"
  | "share"
  | "share_a"
  | "share_b"
  | "shift_1"
  | "shift_2"
  | "shift_3"
  | "smile"
  | "sos"
  | "stamp"
  | "star"
  | "star_a"
  | "star_b"
  | "stats"
  | "success"
  | "success_a"
  | "support"
  | "thumb_down"
  | "thumb_down_a"
  | "thumb_down_b"
  | "thumb_up"
  | "thumb_up_a"
  | "thumb_up_b"
  | "timer"
  | "trainings"
  | "trainings_completed"
  | "uncheck"
  | "vibro"
  | "video"
  | "voice"
  | "wallet"
  | "warning"
  | "warning_a"
  | "warning_b"
  | "wheel";

export const getIcon = (name: IconName): React.FC<SVGProps<SVGSVGElement>> => {
  switch (name) {
    case "abc":
      return IconSet.Abc;
    case "apple":
      return IconSet.Apple;
    case "apple_pay":
      return IconSet.ApplePay;
    case "auto_withdraw":
      return IconSet.AutoWithdraw;
    case "award":
      return IconSet.Award;
    case "back_seats":
      return IconSet.BackSeats;
    case "bill":
      return IconSet.Bill;
    case "business":
      return IconSet.Business;
    case "calendar":
      return IconSet.Calendar;
    case "camera_b":
      return IconSet.CameraB;
    case "camera_c":
      return IconSet.CameraC;
    case "camera_d":
      return IconSet.CameraD;
    case "canada":
      return IconSet.Canada;
    case "cancel":
      return IconSet.Cancel;
    case "car_back":
      return IconSet.CarBack;
    case "car_charge":
      return IconSet.CarCharge;
    case "car_child":
      return IconSet.CarChild;
    case "car_fuel":
      return IconSet.CarFuel;
    case "car_mileage":
      return IconSet.CarMileage;
    case "car_pet":
      return IconSet.CarPet;
    case "car_seat":
      return IconSet.CarSeat;
    case "car_trunk":
      return IconSet.CarTrunk;
    case "car_type":
      return IconSet.CarType;
    case "card":
      return IconSet.Card;
    case "card_a":
      return IconSet.CardA;
    case "card_c":
      return IconSet.CardC;
    case "cash":
      return IconSet.Cash;
    case "change":
      return IconSet.Change;
    case "chat":
      return IconSet.Chat;
    case "chat_a":
      return IconSet.ChatA;
    case "check":
      return IconSet.Check;
    case "check_a":
      return IconSet.CheckA;
    case "chevron_down":
      return IconSet.ChevronDown;
    case "chevron_up":
      return IconSet.ChevronUp;
    case "close":
      return IconSet.Close;
    case "close_a":
      return IconSet.CloseA;
    case "color":
      return IconSet.Color;
    case "coordinates":
      return IconSet.Coordinates;
    case "copy":
      return IconSet.Copy;
    case "correct":
      return IconSet.Correct;
    case "delete":
      return IconSet.Delete;
    case "doc":
      return IconSet.Doc;
    case "documents_verified":
      return IconSet.DocumentsVerified;
    case "dollar":
      return IconSet.Dollar;
    case "dot":
      return IconSet.Dot;
    case "double_check":
      return IconSet.DoubleCheck;
    case "download":
      return IconSet.Download;
    case "drag_area":
      return IconSet.DragArea;
    case "edit":
      return IconSet.Edit;
    case "email":
      return IconSet.Email;
    case "empty":
      return IconSet.Empty;
    case "eye":
      return IconSet.Eye;
    case "eye_closed":
      return IconSet.EyeClosed;
    case "facebook":
      return IconSet.Facebook;
    case "favorites":
      return IconSet.Favorites;
    case "favorites_a":
      return IconSet.FavoritesA;
    case "favorites_b":
      return IconSet.FavoritesB;
    case "first_name":
      return IconSet.FirstName;
    case "front_seats":
      return IconSet.FrontSeats;
    case "goal":
      return IconSet.Goal;
    case "google":
      return IconSet.Google;
    case "google_pay":
      return IconSet.GooglePay;
    case "image":
      return IconSet.Image;
    case "information":
      return IconSet.Information;
    case "information_a":
      return IconSet.InformationA;
    case "last_name":
      return IconSet.LastName;
    case "licence_plate":
      return IconSet.LicencePlate;
    case "loading":
      return IconSet.Loading;
    case "location_pin":
      return IconSet.LocationPin;
    case "location_pin_a":
      return IconSet.LocationPinA;
    case "logout":
      return IconSet.Logout;
    case "menu":
      return IconSet.Menu;
    case "minus":
      return IconSet.Minus;
    case "more":
      return IconSet.More;
    case "multi_stops":
      return IconSet.MultiStops;
    case "navigation":
      return IconSet.Navigation;
    case "no_cash":
      return IconSet.NoCash;
    case "notification":
      return IconSet.Notification;
    case "number":
      return IconSet.Number;
    case "passport":
      return IconSet.Passport;
    case "password":
      return IconSet.Password;
    case "pause":
      return IconSet.Pause;
    case "paypal":
      return IconSet.Paypal;
    case "phone_a":
      return IconSet.PhoneA;
    case "phone_b":
      return IconSet.PhoneB;
    case "phone_c":
      return IconSet.PhoneC;
    case "plus":
      return IconSet.Plus;
    case "plus_a":
      return IconSet.PlusA;
    case "point_a":
      return IconSet.PointA;
    case "point_b":
      return IconSet.PointB;
    case "point_c":
      return IconSet.PointC;
    case "post":
      return IconSet.Post;
    case "profile":
      return IconSet.Profile;
    case "progress":
      return IconSet.Progress;
    case "promo":
      return IconSet.Promo;
    case "promo_applied":
      return IconSet.PromoApplied;
    case "question":
      return IconSet.Question;
    case "repeat":
      return IconSet.Repeat;
    case "report":
      return IconSet.Report;
    case "return":
      return IconSet.Return;
    case "reverse":
      return IconSet.Reverse;
    case "ride":
      return IconSet.Ride;
    case "route":
      return IconSet.Route;
    case "search":
      return IconSet.Search;
    case "settings":
      return IconSet.Settings;
    case "settings_a":
      return IconSet.SettingsA;
    case "share":
      return IconSet.Share;
    case "share_a":
      return IconSet.ShareA;
    case "share_b":
      return IconSet.ShareB;
    case "shift_1":
      return IconSet.Shift1;
    case "shift_2":
      return IconSet.Shift2;
    case "shift_3":
      return IconSet.Shift3;
    case "smile":
      return IconSet.Smile;
    case "sos":
      return IconSet.Sos;
    case "stamp":
      return IconSet.Stamp;
    case "star":
      return IconSet.Star;
    case "star_a":
      return IconSet.StarA;
    case "star_b":
      return IconSet.StarB;
    case "stats":
      return IconSet.Stats;
    case "success":
      return IconSet.Success;
    case "success_a":
      return IconSet.SuccessA;
    case "support":
      return IconSet.Support;
    case "thumb_down":
      return IconSet.ThumbDown;
    case "thumb_down_a":
      return IconSet.ThumbDownA;
    case "thumb_down_b":
      return IconSet.ThumbDownB;
    case "thumb_up":
      return IconSet.ThumbUp;
    case "thumb_up_a":
      return IconSet.ThumbUpA;
    case "thumb_up_b":
      return IconSet.ThumbUpB;
    case "timer":
      return IconSet.Timer;
    case "trainings":
      return IconSet.Trainings;
    case "trainings_completed":
      return IconSet.TrainingsCompleted;
    case "uncheck":
      return IconSet.Uncheck;
    case "vibro":
      return IconSet.Vibro;
    case "video":
      return IconSet.Video;
    case "voice":
      return IconSet.Voice;
    case "wallet":
      return IconSet.Wallet;
    case "warning":
      return IconSet.Warning;
    case "warning_a":
      return IconSet.WarningA;
    case "warning_b":
      return IconSet.WarningB;
    case "wheel":
      return IconSet.Wheel;
  }
};

export const getSize = (size: IconSize) => {
  switch (size) {
    case "xs":
      return 18;
    case "sm":
      return 24;
    case "md":
      return 36;
    case "lg":
      return 48;
    case "xl":
      return 72;
    case "xxl":
      return 144;
  }
};
